name: Build Release

on:
  push:
    branches-ignore:
      - '*'
    tags:
      - 'v*.*.*'

jobs:
  build-webos:
    name: Build WebOS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          curl https://mateussouzaweb.github.io/compactor/install.sh | bash
          npm install
          npm install --global rollup

      - name: Build package
        run: |
          npm run build
          npm run app-package
          npm run app-manifest

      - name: Create tag release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            LICENSE.md
            bin/*.ipk
            bin/webosbrew.manifest.json