name: Build Test

on:
  push:
    tags-ignore:
      - 'v*.*.*'
    branches:
      - '*'

jobs:
  build-webos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        run: |
          curl https://mateussouzaweb.github.io/compactor/install.sh | bash
          npm install
          npm install --global rollup

      - name: Build package
        run: |
          npm run build
          npm run app-package
          npm run app-manifest

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: webos-snapshot
          path: |
            bin/*.ipk
            bin/webosbrew.manifest.json
